import { TurfStatus } from "@/interface/enum.interface";
import { ITurf } from "@/interface/turf.interface";

/** Showcase turfs for the home page — mapped to ITurf for TurfCard reuse */
export const POPULAR_TURFS: ITurf[] = [
  {
    id: "1",
    createdAt: "",
    updatedAt: "",
    name: "Emerald Arena North",
    address: "Dhaka, BD",
    contactNumber: [],
    isVerifiedEmail: true,
    images: ["/images/turf-football.png"],
    openingTime: "06:00",
    closingTime: "23:00",
    weeklyOffDays: [],
    isAlwaysOpen: false,
    saveCount: 0,
    turfStatus: TurfStatus.ACTIVE,
    rating: 4.9,
    reviewCount: 0,
    hourlyRate: "1200",
    ownerId: "showcase-1",
    sportTypes: [{ id: "s1", title: "Football", icon: "football", createdAt: "", updatedAt: "" }],
  },
  {
    id: "2",
    createdAt: "",
    updatedAt: "",
    name: "Elite Indoor Arena",
    address: "Chittagong, BD",
    contactNumber: [],
    isVerifiedEmail: true,
    images: ["/images/turf-multi.png"],
    openingTime: "08:00",
    closingTime: "22:00",
    weeklyOffDays: [],
    isAlwaysOpen: false,
    saveCount: 0,
    turfStatus: TurfStatus.ACTIVE,
    rating: 4.8,
    reviewCount: 0,
    hourlyRate: "1500",
    ownerId: "showcase-2",
    sportTypes: [{ id: "s2", title: "Multi-sport", icon: "multi", createdAt: "", updatedAt: "" }],
  },
  {
    id: "3",
    createdAt: "",
    updatedAt: "",
    name: "Stadium Lights Cricket",
    address: "Sylhet, BD",
    contactNumber: [],
    isVerifiedEmail: true,
    images: ["/images/turf-cricket.png"],
    openingTime: "07:00",
    closingTime: "21:00",
    weeklyOffDays: [],
    isAlwaysOpen: false,
    saveCount: 0,
    turfStatus: TurfStatus.ACTIVE,
    rating: 4.9,
    reviewCount: 0,
    hourlyRate: "1100",
    ownerId: "showcase-3",
    sportTypes: [{ id: "s3", title: "Cricket", icon: "cricket", createdAt: "", updatedAt: "" }],
  },
];
